package com.example.modernandroidapp.ui.theme

import androidx.compose.ui.graphics.Color

// Blueberry Brand Colors
val SpaceCadet = Color(0xFF1F3050)      // Primary
val AmericanBlue = Color(0xFF2A416F)    // Secondary
val QueenBlue = Color(0xFF496898)       // Accent/Tertiary

// Light Theme Colors (2025 Modern Design)
val md_theme_light_primary = Color(0xFF4F46E5)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE0E7FF)
val md_theme_light_onPrimaryContainer = Color(0xFF1E1B4B)
val md_theme_light_secondary = Color(0xFF6366F1)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFEEF2FF)
val md_theme_light_onSecondaryContainer = Color(0xFF1E1B4B)
val md_theme_light_tertiary = Color(0xFF8B5CF6)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFF3E8FF)
val md_theme_light_onTertiaryContainer = Color(0xFF2E1065)
val md_theme_light_error = Color(0xFFEF4444)
val md_theme_light_errorContainer = Color(0xFFFEF2F2)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF7F1D1D)
val md_theme_light_background = Color(0xFFF9FAFB)
val md_theme_light_onBackground = Color(0xFF111827)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF111827)
val md_theme_light_surfaceVariant = Color(0xFFF3F4F6)
val md_theme_light_onSurfaceVariant = Color(0xFF6B7280)
val md_theme_light_outline = Color(0xFFD1D5DB)
val md_theme_light_inverseOnSurface = Color(0xFFF9FAFB)
val md_theme_light_inverseSurface = Color(0xFF111827)
val md_theme_light_inversePrimary = Color(0xFFC7D2FE)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF4F46E5)
val md_theme_light_outlineVariant = Color(0xFFE5E7EB)
val md_theme_light_scrim = Color(0xFF000000)

// Dark Theme Colors (Optional but clean)
val md_theme_dark_primary = Color(0xFFC7D2FE)
val md_theme_dark_onPrimary = Color(0xFF1E1B4B)
val md_theme_dark_primaryContainer = Color(0xFF3730A3)
val md_theme_dark_onPrimaryContainer = Color(0xFFE0E7FF)
val md_theme_dark_secondary = Color(0xFFC7D2FE)
val md_theme_dark_onSecondary = Color(0xFF1E1B4B)
val md_theme_dark_secondaryContainer = Color(0xFF3730A3)
val md_theme_dark_onSecondaryContainer = Color(0xFFE0E7FF)
val md_theme_dark_tertiary = Color(0xFFDDD6FE)
val md_theme_dark_onTertiary = Color(0xFF2E1065)
val md_theme_dark_tertiaryContainer = Color(0xFF5B21B6)
val md_theme_dark_onTertiaryContainer = Color(0xFFF3E8FF)
val md_theme_dark_error = Color(0xFFFCA5A5)
val md_theme_dark_errorContainer = Color(0xFF7F1D1D)
val md_theme_dark_onError = Color(0xFF000000)
val md_theme_dark_onErrorContainer = Color(0xFFFEF2F2)
val md_theme_dark_background = Color(0xFF111827)
val md_theme_dark_onBackground = Color(0xFFF9FAFB)
val md_theme_dark_surface = Color(0xFF1F2937)
val md_theme_dark_onSurface = Color(0xFFF9FAFB)
val md_theme_dark_surfaceVariant = Color(0xFF374151)
val md_theme_dark_onSurfaceVariant = Color(0xFF9CA3AF)
val md_theme_dark_outline = Color(0xFF4B5563)
val md_theme_dark_inverseOnSurface = Color(0xFF111827)
val md_theme_dark_inverseSurface = Color(0xFFF9FAFB)
val md_theme_dark_inversePrimary = Color(0xFF4F46E5)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFC7D2FE)
val md_theme_dark_outlineVariant = Color(0xFF374151)
val md_theme_dark_scrim = Color(0xFF000000)

// Custom Status Colors
val status_pending = Color(0xFFF59E0B)
val status_completed = Color(0xFF10B981)
val status_error = Color(0xFFEF4444)
val status_info = Color(0xFF3B82F6)

// Custom Background Colors
val background_primary = Color(0xFFF9FAFB)
val background_secondary = Color(0xFFFFFFFF)
val background_tertiary = Color(0xFFF3F4F6)

// Legacy colors for backward compatibility
val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)
val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260) 